In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
from sklearn import linear_model
from statsmodels.formula.api import ols

induced_data = pd.read_csv('induced_genes_outliers_removed_all_zero_removed.csv')
induced_data = induced_data.iloc[:,1:]

#grp1 = ['IFITM3','SRGN','IL1RN','IFI27L2A','TNF','IFI205','TARM1','TNFSF9','IRG1','GLIPR2','INHBA','BTG1','PSME2','CLEC4E','2310016C08RIK','SQSTM1','NFKBIA','USP18','EBI3','CD86','MS4A6D','NT5C3','FPR2','H3F3B','SERPINA3G','CAV1','FAS','MS4A6C','LGALS9','GM4902','CD200','IFI204','CISH','PROCR','SLAMF7','AI607873','SGK1','IL15','ACPP','CXCL16','SLFN2','H2-Q7','MT2','H2-T23','THBS1','UBE2L6','AY096003','H1F0','ATF3','TANK','TNFSF15','HSPA5','IL15RA','IRF1','MED21','IRGM1','CCRL2','ZBP1','CASP1','RAB32','SP100','IRF8','BLNK','PSMB9','PCGF5','KTELC1','RILPL2','TMEM39A','TRIM30A','TNIP3','RBM7','SLC2A6','GBP3','BIRC3','TLR2','GTF2B','CFB','SBDS','CAR13','ARF4','SEPW1','BST2','NMI','DUSP1','PYHIN1','CD47','ZFP36','CD274','SAMHD1','SWAP70','IL7R','RELA','AK042010','A130040M12RIK','D14ERTD668E','NFKBIZ','ADAP2','XAF1','PNP','ZUFSP','IFI35','ACSL1','ANXA7','SLC7A2','HERC6','TAPBP','SLFN5','SLFN8','IFIH1','FGL2','LCP2','STAT1','GBP5','TRIM30D','LAP3','STAT5A','GBP6','DDX58','CLIC4','DHX58','STAT2','TNFAIP3','TAP1','ELL2','PIK3R5','PARP9','KPNA3','HIF1A','AFTPH','DTX3L']
#grp2 = ['SDC4','CXCL1','IL1A','CXCL3','IL1B','CCL3','AW112010','CCL17','PRDX1','CCL4','H2-M2']
#with open("global_regressions/summary.csv","w") as logfile:
#    logfile.write("gene,scoreAll\n")


#glist=['CCL5','CCL17','AK217941','AK138792','PRDX1','CXCL10','APOL7C','AW112010','IL1B','CXCL1','CCL3','SDC4','H2-M2','LY6C2','CLU','IL1A','ZDHHC21','CXCL3','CCR7','CD14','CD69','BCL2A1B','IFI27L2A','SLPI','SERPINB9','IFITM3','AA467197','GLIPR2','MX1','TNF','TARM1','BCL2A1D','CLEC4D','IRG1','CD40','BCL2A1A','USP18','SAMSN1','CLEC4E','CAR4','1810029B16RIK','CD86','SQSTM1','SERPINB6B','RNASET2B','MS4A6D','NUPR1','P2RY14','2310016C08RIK','H2-Q7','FOS','GBP2','CDKN1A','NFKBIA','FPR1','EBI3','FPR2','SAMHD1','UBE2L6','IFIT2','MS4A6C','ARF4','STXBP3A','AY096003','EPSTI1','TNIP3','AI607873','SLAMF7','CD200','RAB8B','MT2','SLFN2','HSPA5','BIRC3','IRGM1','MARCKSL1','TMEM39A','ETV3','TREX1','PROCR','BLNK','RELA','RTP4','CCRL2','TRIM30A','BHLHE40','PLAUR','KYNU','TLR2','BST2','SWAP70','ZBP1','SP100','GBP3','PCGF5','KTELC1','IRF8','IGTP','SOD2','CISH','TNFSF15','MNDAL','CFB','PLEK','PNP','ZFP36','NMI','SLC2A6','H1F0','SBDS','XAF1','NFKBIZ','TRAF1','PYHIN1','MTPN','SLC7A2','APOBEC3','CD274','TAPBP','LGALS3BP','KTN1','PPP1CB','ZUFSP','PTTG1','IFIH1','GM4951','BATF','ADAP2','IFI203','IFI35','GADD45B','PELI1','STAT1','LCP2','STAT2','GBP6','KPNA3','SLFN5','GBP5','PFKP','TAP1','TOR3A','INSIG1','DAB2','AFTPH','TXNRD1']

regression_data=pd.read_csv('summary_mean_var_all_cond.csv')
glist=regression_data.iloc[:,0].tolist();

In [7]:
x

array([  3.04802783e+01,   4.54950095e+02,   8.38031117e+02,
         7.10301238e+02,   9.72864922e+02,   1.41244583e+02,
         1.08086040e+03,   8.14579840e+02,   2.01483062e+02,
         3.21550343e+02,   1.18444405e+01,   4.50396451e+01,
         1.57874524e+03,   2.02917395e+02,   1.01740475e+02,
         1.59641919e+03,   2.87951322e-01,   2.90803889e+03,
         3.32398058e+02,   1.08762771e+03,   4.85120121e+01,
         1.74788576e+03,   2.64619210e+03,   1.52172552e+03,
         8.73531625e+00,   4.56399480e+02])

In [3]:
#print(induced_data.head)

#genelist = induced_data.iloc[:,0].reset_index(drop=True).drop_duplicates().tolist()
#genelist += [genelist.pop(24)] #manually moving index 24 TNF to end so visible on plots

i=0

plt.subplots(1,1,figsize=(5,4.5))
axes = plt.gca()
axes.set_xlim([0,3000])
axes.set_ylim([0,4])

with open("my_summary_mean_freq_all_conds_robust.csv","a") as logfile:
        logfile.write("%s,%s,%s,%s,%s,%s,%s,\n" % ('gene','N','intercept','slope','min x','max x','R2'))



for test_gene in glist:
    i+=1
    print(i)
    summary_stats = induced_data[induced_data["Gene"]==test_gene]
    #print(summary_stats)
    if (len(summary_stats.loc[summary_stats['Mean'] == 0,['Mean']])>0) :
        print("Missing data for %s" % test_gene)
        with open("errorlog.csv","a") as logfile:
            logfile.write("%s\n" % test_gene)
        continue
    
    print("Working on %s mean/freq regression..." % test_gene)
    

    x=np.ravel(summary_stats['Mean'].values.reshape(-1, 1))
    #print(x)
    y=np.ravel(summary_stats['Frequency'].values.reshape(-1, 1))
    x=x.reshape(-1, 1)
    y=y.reshape(-1, 1)
    
    lm = linear_model.LinearRegression()
    model = lm.fit(x,y)
    
    Fy=lm.predict(x)
    Residuals=y-Fy;   
    I = abs( Residuals) < 1.5 * np.std(Residuals);
    x1=x[I==True]
    y1=y[I==True]
    x1=x1.reshape(-1, 1)
    y1=y1.reshape(-1, 1)
    
    model = lm.fit(x1,y1)
    print("Intercept:\t",lm.intercept_)
    print("Coefficients:\t",lm.coef_)
    scoreAll = lm.score(x1,y1)
    print("R^2 score:\t",scoreAll)

    linecol = 'gray'

    """
    if(test_gene == 'TNF') :
        linecol = 'red'
    elif(test_gene == 'IL1A'):
        linecol = 'blue'
    elif(test_gene == 'IL1B'):
        linecol = 'green'
    elif(test_gene == 'CCL4'):
        linecol = 'orange'
    elif(test_gene == 'CCL17'):
        linecol = 'purple'
    """
    
    #if test_gene in glist:
        
    plt.plot(x1, lm.predict(x1), color=linecol, linewidth=1)

    with open("my_summary_mean_freq_all_conds_robust.csv","a") as logfile:
        logfile.write("%s,%s,%s,%s,%s,%s,%s,\n" % (test_gene,len(x1),float(lm.intercept_),float(lm.coef_),float(min(x1)), float(max(x1)), scoreAll))
        print("%s,%s\n" % (test_gene,scoreAll))

plt.ylabel("Freq")
plt.xlabel("Mean")
#plt.savefig("global_regressions/mean_var_composite.png")
plt.savefig("my_mean_freq_allconds_robust.png")
plt.close()




1
Working on CXCL1 mean/freq regression...
Intercept:	 [ 0.03611044]
Coefficients:	 [[ 0.00019401]]
R^2 score:	 0.967931043116
CXCL1,0.967931043116

2
Working on RSAD2 mean/freq regression...
Intercept:	 [ 0.09068904]
Coefficients:	 [[ 0.00066543]]
R^2 score:	 0.970177018088
RSAD2,0.970177018088

3
Working on OASL1 mean/freq regression...
Intercept:	 [ 0.04474974]
Coefficients:	 [[ 0.00153364]]
R^2 score:	 0.981545726973
OASL1,0.981545726973

4
Working on NT5C3 mean/freq regression...
Intercept:	 [ 0.06794898]
Coefficients:	 [[ 0.00139625]]
R^2 score:	 0.972266642735
NT5C3,0.972266642735

5
Working on CCL4 mean/freq regression...
Intercept:	 [ 0.06270197]
Coefficients:	 [[  7.11916434e-05]]
R^2 score:	 0.972681325753
CCL4,0.972681325753

6
Working on EBI3 mean/freq regression...
Intercept:	 [ 0.09529567]
Coefficients:	 [[ 0.00092637]]
R^2 score:	 0.85121056209
EBI3,0.85121056209

7
Working on IRGM1 mean/freq regression...
Intercept:	 [ 0.07593068]
Coefficients:	 [[ 0.00193886]]
R^2 sco

R^2 score:	 0.791807356897
CLU,0.791807356897

117
Working on 2310016C08RIK mean/freq regression...
Intercept:	 [-0.0032827]
Coefficients:	 [[ 0.00122957]]
R^2 score:	 0.915039790635
2310016C08RIK,0.915039790635

118
Working on KPNA3 mean/freq regression...
Intercept:	 [ 0.12899231]
Coefficients:	 [[ 0.0048404]]
R^2 score:	 0.802029874991
KPNA3,0.802029874991

119
Working on GLIPR2 mean/freq regression...
Intercept:	 [ 0.08086525]
Coefficients:	 [[ 0.00069049]]
R^2 score:	 0.697966357083
GLIPR2,0.697966357083

120
Working on XAF1 mean/freq regression...
Intercept:	 [ 0.04076306]
Coefficients:	 [[ 0.00346152]]
R^2 score:	 0.892018348183
XAF1,0.892018348183

121
Working on SLC7A2 mean/freq regression...
Intercept:	 [ 0.19221026]
Coefficients:	 [[ 0.00279471]]
R^2 score:	 0.692330918042
SLC7A2,0.692330918042

122
Working on PROCR mean/freq regression...
Intercept:	 [ 0.03062903]
Coefficients:	 [[ 0.00180904]]
R^2 score:	 0.840687760932
PROCR,0.840687760932

123
Working on PRPF38A mean/fre


205
Working on A130040M12RIK mean/freq regression...
Intercept:	 [ 0.07908495]
Coefficients:	 [[ 0.00322358]]
R^2 score:	 0.818797250495
A130040M12RIK,0.818797250495

206
Working on PNP mean/freq regression...
Intercept:	 [ 0.128649]
Coefficients:	 [[ 0.00329657]]
R^2 score:	 0.79347467356
PNP,0.79347467356

207
Working on SP140 mean/freq regression...
Intercept:	 [ 0.14205375]
Coefficients:	 [[ 0.00291766]]
R^2 score:	 0.853698254766
SP140,0.853698254766

208
Working on BHLHE40 mean/freq regression...
Intercept:	 [ 0.13563563]
Coefficients:	 [[ 0.00178787]]
R^2 score:	 0.600952331848
BHLHE40,0.600952331848

209
Working on CXCL16 mean/freq regression...
Intercept:	 [ 0.22708908]
Coefficients:	 [[ 0.00136164]]
R^2 score:	 0.638156702846
CXCL16,0.638156702846

210
Working on MAP2K1 mean/freq regression...
Intercept:	 [ 0.08773593]
Coefficients:	 [[ 0.00336167]]
R^2 score:	 0.535202124394
MAP2K1,0.535202124394

211
Working on RASGEF1B mean/freq regression...
Intercept:	 [ 0.07259903]
Coe

In [10]:
x1

array([[  415.42631491],
       [ 1083.28813642],
       [  432.64161359],
       [  588.52541452],
       [  786.0472841 ],
       [  675.28670075],
       [  426.63907959],
       [  438.06328826],
       [  593.26476283],
       [  915.02621588],
       [  729.10019489],
       [  529.31792485],
       [  509.53069838],
       [  333.68231193],
       [  388.03384699],
       [  281.59506739],
       [  457.62964107],
       [ 1289.35629098],
       [  836.9740624 ],
       [  791.7523987 ],
       [  707.76427944],
       [  762.05792869]])

In [11]:
lm.predict(x1)


array([[ 1311.58845456],
       [  907.97599171],
       [ 1301.18464215],
       [ 1206.97856122],
       [ 1087.60912629],
       [ 1154.54565476],
       [ 1304.81218524],
       [ 1297.90813286],
       [ 1204.11440582],
       [ 1009.66260706],
       [ 1122.02426156],
       [ 1242.75973624],
       [ 1254.71785535],
       [ 1360.98923972],
       [ 1328.14268941],
       [ 1392.46739939],
       [ 1286.0834955 ],
       [  783.44173523],
       [ 1056.83227732],
       [ 1084.16132425],
       [ 1134.91830806],
       [ 1102.10674018]])

In [12]:
print(lm.intercept_)

37967.2236598
